rccola:
  args:
    url: https://redcap.vanderbilt.edu/api/
  keys:
    redcap_data: <REDCap API key>
brs:
  report:
    directory: <directory>
    cron:
      min:  0
      hour: 0
    error:
      to: matt.shotwell@vumc.org 
      subject: "BRS Test Error"
      template: "BRS Test report encountered an error."
    output:
      email:
        to: matt.shotwell@vumc.org 
        subject: "BRS Test" 
        template: "Please see the attached BRS Test report." 
    command: Rscript render.R
    ext: html
    log: INFO
